from grade import Grade
from grade_class import GradeClass
from school import School
from student import Student
from subjects import Subject
from teacher import Teacher

math_sub = Subject(name="math")
serbian_sub = Subject(name="serbian")
physical_sub = Subject(name="physical")
world_around_us_sub = Subject(name="world around us")
music_sub = Subject(name="music")
art_sub = Subject(name="art")
english_sub = Subject(name="english")
nature_and_society_sub = Subject(name="nature and society")
history_sub = Subject(name="history")
geography_sub = Subject(name="geography")
biology_sub = Subject(name="biology")
technology_sub = Subject(name="technology")
computer_science_sub = Subject(name="computer science")
physics_sub = Subject(name="physics")
chemistry_sub = Subject(name="chemistry")


school_ck = School(name="OŠ Ćele kula", teachers=[], students=[], id="ck")


first_grade_ck = Grade(grade_num="I", students=[], subjects=[])
first_grade_ck.add_subject(subject=math_sub)
first_grade_ck.add_subject(subject=serbian_sub)
first_grade_ck.add_subject(subject=english_sub)
first_grade_ck.add_subject(subject=physical_sub)
first_grade_ck.add_subject(subject=world_around_us_sub)
first_grade_ck.add_subject(subject=music_sub)
first_grade_ck.add_subject(subject=art_sub)
grade_class_1_first_grade_ck = GradeClass(grade= "I", grade_class_num= "1")
grade_class_2_first_grade_ck = GradeClass(grade= "I", grade_class_num= "2")
first_grade_ck.add_grade_class(grade_class=grade_class_1_first_grade_ck)
first_grade_ck.add_grade_class(grade_class=grade_class_2_first_grade_ck)

second_grade_ck = Grade(grade_num="II", students=[], subjects=[])
second_grade_ck.add_subject(subject=math_sub)
second_grade_ck.add_subject(subject=serbian_sub)
second_grade_ck.add_subject(subject=english_sub)
second_grade_ck.add_subject(subject=physical_sub)
second_grade_ck.add_subject(subject=world_around_us_sub)
second_grade_ck.add_subject(subject=music_sub)
second_grade_ck.add_subject(subject=art_sub)
grade_class_1_second_grade_ck = GradeClass(grade= "II", grade_class_num= "1")
grade_class_2_second_grade_ck = GradeClass(grade= "II", grade_class_num= "2")
second_grade_ck.add_grade_class(grade_class=grade_class_1_second_grade_ck)
second_grade_ck.add_grade_class(grade_class=grade_class_2_second_grade_ck)

third_grade_ck = Grade(grade_num="III", students=[], subjects=[])
third_grade_ck.add_subject(subject=math_sub)
third_grade_ck.add_subject(subject=serbian_sub)
third_grade_ck.add_subject(subject=english_sub)
third_grade_ck.add_subject(subject=physical_sub)
third_grade_ck.add_subject(subject=nature_and_society_sub)
third_grade_ck.add_subject(subject=music_sub)
third_grade_ck.add_subject(subject=art_sub)
grade_class_1_third_grade_ck = GradeClass(grade= "III", grade_class_num= "1")
grade_class_2_third_grade_ck = GradeClass(grade= "III", grade_class_num= "2")
third_grade_ck.add_grade_class(grade_class=grade_class_1_third_grade_ck)
third_grade_ck.add_grade_class(grade_class=grade_class_2_third_grade_ck)

fourth_grade_ck = Grade(grade_num="IV", students=[], subjects=[])
fourth_grade_ck.add_subject(subject=math_sub)
fourth_grade_ck.add_subject(subject=serbian_sub)
fourth_grade_ck.add_subject(subject=english_sub)
fourth_grade_ck.add_subject(subject=physical_sub)
fourth_grade_ck.add_subject(subject=nature_and_society_sub)
fourth_grade_ck.add_subject(subject=music_sub)
fourth_grade_ck.add_subject(subject=art_sub)
grade_class_1_fourth_grade_ck = GradeClass(grade= "IV", grade_class_num= "1")
grade_class_2_fourth_grade_ck = GradeClass(grade= "IV", grade_class_num= "2")
fourth_grade_ck.add_grade_class(grade_class=grade_class_1_fourth_grade_ck)
fourth_grade_ck.add_grade_class(grade_class=grade_class_2_fourth_grade_ck)

fifth_grade_ck = Grade(grade_num="V", students=[], subjects=[])
fifth_grade_ck.add_subject(subject=math_sub)
fifth_grade_ck.add_subject(subject=serbian_sub)
fifth_grade_ck.add_subject(subject=english_sub)
fifth_grade_ck.add_subject(subject=physical_sub)
fifth_grade_ck.add_subject(subject=music_sub)
fifth_grade_ck.add_subject(subject=art_sub)
fifth_grade_ck.add_subject(subject=history_sub)
fifth_grade_ck.add_subject(subject=biology_sub)
fifth_grade_ck.add_subject(subject=geography_sub)
grade_class_1_fifth_grade_ck = GradeClass(grade= "V", grade_class_num= "1")
grade_class_2_fifth_grade_ck = GradeClass(grade= "V", grade_class_num= "2")
fifth_grade_ck.add_grade_class(grade_class=grade_class_1_fifth_grade_ck)
fifth_grade_ck.add_grade_class(grade_class=grade_class_2_fifth_grade_ck)

sixth_grade_ck = Grade(grade_num="VI", students=[], subjects=[])
sixth_grade_ck.add_subject(subject=math_sub)
sixth_grade_ck.add_subject(subject=serbian_sub)
sixth_grade_ck.add_subject(subject=english_sub)
sixth_grade_ck.add_subject(subject=physical_sub)
sixth_grade_ck.add_subject(subject=music_sub)
sixth_grade_ck.add_subject(subject=art_sub)
sixth_grade_ck.add_subject(subject=history_sub)
sixth_grade_ck.add_subject(subject=biology_sub)
sixth_grade_ck.add_subject(subject=geography_sub)
sixth_grade_ck.add_subject(subject=physics_sub)
grade_class_1_sixth_grade_ck = GradeClass(grade= "VI", grade_class_num= "1")
grade_class_2_sixth_grade_ck = GradeClass(grade= "VI", grade_class_num= "2")
sixth_grade_ck.add_grade_class(grade_class=grade_class_1_sixth_grade_ck)
sixth_grade_ck.add_grade_class(grade_class=grade_class_2_sixth_grade_ck)

seventh_grade_ck = Grade(grade_num="VII", students=[], subjects=[])
seventh_grade_ck.add_subject(subject=math_sub)
seventh_grade_ck.add_subject(subject=serbian_sub)
seventh_grade_ck.add_subject(subject=english_sub)
seventh_grade_ck.add_subject(subject=physical_sub)
seventh_grade_ck.add_subject(subject=music_sub)
seventh_grade_ck.add_subject(subject=art_sub)
seventh_grade_ck.add_subject(subject=history_sub)
seventh_grade_ck.add_subject(subject=biology_sub)
seventh_grade_ck.add_subject(subject=geography_sub)
seventh_grade_ck.add_subject(subject=physics_sub)
seventh_grade_ck.add_subject(subject=chemistry_sub)
grade_class_1_seventh_grade_ck = GradeClass(grade= "VII", grade_class_num= "1")
grade_class_2_seventh_grade_ck = GradeClass(grade= "VII", grade_class_num= "2")
seventh_grade_ck.add_grade_class(grade_class=grade_class_1_seventh_grade_ck)
seventh_grade_ck.add_grade_class(grade_class=grade_class_2_seventh_grade_ck)

eight_grade_ck = Grade(grade_num="VIII", students=[], subjects=[])
eight_grade_ck.add_subject(subject=math_sub)
eight_grade_ck.add_subject(subject=serbian_sub)
eight_grade_ck.add_subject(subject=english_sub)
eight_grade_ck.add_subject(subject=physical_sub)
eight_grade_ck.add_subject(subject=music_sub)
eight_grade_ck.add_subject(subject=art_sub)
eight_grade_ck.add_subject(subject=history_sub)
eight_grade_ck.add_subject(subject=biology_sub)
eight_grade_ck.add_subject(subject=geography_sub)
eight_grade_ck.add_subject(subject=physics_sub)
eight_grade_ck.add_subject(subject=chemistry_sub)
grade_class_1_eight_grade_ck = GradeClass(grade= "VIII", grade_class_num= "1")
grade_class_2_eight_grade_ck = GradeClass(grade= "VIII", grade_class_num= "2")
eight_grade_ck.add_grade_class(grade_class=grade_class_1_eight_grade_ck)
eight_grade_ck.add_grade_class(grade_class=grade_class_2_eight_grade_ck)


school_ss = School(name="OŠ Sveti Sava", teachers=[], students=[], id="ss")


first_grade_ss = Grade(grade_num="I", students=[], subjects=[])
first_grade_ss.add_subject(subject=math_sub)
first_grade_ss.add_subject(subject=serbian_sub)
first_grade_ss.add_subject(subject=english_sub)
first_grade_ss.add_subject(subject=physical_sub)
first_grade_ss.add_subject(subject=world_around_us_sub)
first_grade_ss.add_subject(subject=music_sub)
first_grade_ss.add_subject(subject=art_sub)
grade_class_1_first_grade_ss = GradeClass(grade= "I", grade_class_num= "1")
grade_class_2_first_grade_ss = GradeClass(grade= "I", grade_class_num= "2")
first_grade_ss.add_grade_class(grade_class=grade_class_1_first_grade_ss)
first_grade_ss.add_grade_class(grade_class=grade_class_2_first_grade_ss)

second_grade_ss = Grade(grade_num="II", students=[], subjects=[])
second_grade_ss.add_subject(subject=math_sub)
second_grade_ss.add_subject(subject=serbian_sub)
second_grade_ss.add_subject(subject=english_sub)
second_grade_ss.add_subject(subject=physical_sub)
second_grade_ss.add_subject(subject=world_around_us_sub)
second_grade_ss.add_subject(subject=music_sub)
second_grade_ss.add_subject(subject=art_sub)
grade_class_1_second_grade_ss = GradeClass(grade= "II", grade_class_num= "1")
grade_class_2_second_grade_ss = GradeClass(grade= "II", grade_class_num= "2")
second_grade_ss.add_grade_class(grade_class=grade_class_1_second_grade_ss)
second_grade_ss.add_grade_class(grade_class=grade_class_2_second_grade_ss)

third_grade_ss = Grade(grade_num="III", students=[], subjects=[])
third_grade_ss.add_subject(subject=math_sub)
third_grade_ss.add_subject(subject=serbian_sub)
third_grade_ss.add_subject(subject=english_sub)
third_grade_ss.add_subject(subject=physical_sub)
third_grade_ss.add_subject(subject=nature_and_society_sub)
third_grade_ss.add_subject(subject=music_sub)
third_grade_ss.add_subject(subject=art_sub)
grade_class_1_third_grade_ss = GradeClass(grade= "III", grade_class_num= "1")
grade_class_2_third_grade_ss = GradeClass(grade= "III", grade_class_num= "2")
third_grade_ss.add_grade_class(grade_class=grade_class_1_third_grade_ss)
third_grade_ss.add_grade_class(grade_class=grade_class_2_third_grade_ss)

fourth_grade_ss = Grade(grade_num="IV", students=[], subjects=[])
fourth_grade_ss.add_subject(subject=math_sub)
fourth_grade_ss.add_subject(subject=serbian_sub)
fourth_grade_ss.add_subject(subject=english_sub)
fourth_grade_ss.add_subject(subject=physical_sub)
fourth_grade_ss.add_subject(subject=nature_and_society_sub)
fourth_grade_ss.add_subject(subject=music_sub)
fourth_grade_ss.add_subject(subject=art_sub)
grade_class_1_fourth_grade_ss = GradeClass(grade= "IV", grade_class_num= "1")
grade_class_2_fourth_grade_ss = GradeClass(grade= "IV", grade_class_num= "2")
fourth_grade_ss.add_grade_class(grade_class=grade_class_1_fourth_grade_ss)
fourth_grade_ss.add_grade_class(grade_class=grade_class_2_fourth_grade_ss)

fifth_grade_ss = Grade(grade_num="V", students=[], subjects=[])
fifth_grade_ss.add_subject(subject=math_sub)
fifth_grade_ss.add_subject(subject=serbian_sub)
fifth_grade_ss.add_subject(subject=english_sub)
fifth_grade_ss.add_subject(subject=physical_sub)
fifth_grade_ss.add_subject(subject=music_sub)
fifth_grade_ss.add_subject(subject=art_sub)
fifth_grade_ss.add_subject(subject=history_sub)
fifth_grade_ss.add_subject(subject=biology_sub)
fifth_grade_ss.add_subject(subject=geography_sub)
grade_class_1_fifth_grade_ss = GradeClass(grade= "V", grade_class_num= "1")
grade_class_2_fifth_grade_ss = GradeClass(grade= "V", grade_class_num= "2")
fifth_grade_ss.add_grade_class(grade_class=grade_class_1_fifth_grade_ss)
fifth_grade_ss.add_grade_class(grade_class=grade_class_2_fifth_grade_ss)

sixth_grade_ss = Grade(grade_num="VI", students=[], subjects=[])
sixth_grade_ss.add_subject(subject=math_sub)
sixth_grade_ss.add_subject(subject=serbian_sub)
sixth_grade_ss.add_subject(subject=english_sub)
sixth_grade_ss.add_subject(subject=physical_sub)
sixth_grade_ss.add_subject(subject=music_sub)
sixth_grade_ss.add_subject(subject=art_sub)
sixth_grade_ss.add_subject(subject=history_sub)
sixth_grade_ss.add_subject(subject=biology_sub)
sixth_grade_ss.add_subject(subject=geography_sub)
sixth_grade_ss.add_subject(subject=physics_sub)
grade_class_1_sixth_grade_ss = GradeClass(grade= "VI", grade_class_num= "1")
grade_class_2_sixth_grade_ss = GradeClass(grade= "VI", grade_class_num= "2")
sixth_grade_ss.add_grade_class(grade_class=grade_class_1_sixth_grade_ss)
sixth_grade_ss.add_grade_class(grade_class=grade_class_2_sixth_grade_ss)

seventh_grade_ss = Grade(grade_num="VII", students=[], subjects=[])
seventh_grade_ss.add_subject(subject=math_sub)
seventh_grade_ss.add_subject(subject=serbian_sub)
seventh_grade_ss.add_subject(subject=english_sub)
seventh_grade_ss.add_subject(subject=physical_sub)
seventh_grade_ss.add_subject(subject=music_sub)
seventh_grade_ss.add_subject(subject=art_sub)
seventh_grade_ss.add_subject(subject=history_sub)
seventh_grade_ss.add_subject(subject=biology_sub)
seventh_grade_ss.add_subject(subject=geography_sub)
seventh_grade_ss.add_subject(subject=physics_sub)
seventh_grade_ss.add_subject(subject=chemistry_sub)
grade_class_1_seventh_grade_ss = GradeClass(grade= "VII", grade_class_num= "1")
grade_class_2_seventh_grade_ss = GradeClass(grade= "VII", grade_class_num= "2")
seventh_grade_ss.add_grade_class(grade_class=grade_class_1_seventh_grade_ss)
seventh_grade_ss.add_grade_class(grade_class=grade_class_2_seventh_grade_ss)

eight_grade_ss = Grade(grade_num="VIII", students=[], subjects=[])
eight_grade_ss.add_subject(subject=math_sub)
eight_grade_ss.add_subject(subject=serbian_sub)
eight_grade_ss.add_subject(subject=english_sub)
eight_grade_ss.add_subject(subject=physical_sub)
eight_grade_ss.add_subject(subject=music_sub)
eight_grade_ss.add_subject(subject=art_sub)
eight_grade_ss.add_subject(subject=history_sub)
eight_grade_ss.add_subject(subject=biology_sub)
eight_grade_ss.add_subject(subject=geography_sub)
eight_grade_ss.add_subject(subject=physics_sub)
eight_grade_ss.add_subject(subject=chemistry_sub)
grade_class_1_eight_grade_ss = GradeClass(grade= "VIII", grade_class_num= "1")
grade_class_2_eight_grade_ss = GradeClass(grade= "VIII", grade_class_num= "2")
eight_grade_ss.add_grade_class(grade_class=grade_class_1_eight_grade_ss)
eight_grade_ss.add_grade_class(grade_class=grade_class_2_eight_grade_ss)


teacher_1 = Teacher(name="Jasmina", surname="Dimic", jmbg="1205985735012", date_of_birth="12.5.1985.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="100")
teacher_1.add_subject(subject=math_sub)
teacher_1.add_subject(subject=serbian_sub)
teacher_1.add_subject(subject=english_sub)
teacher_1.add_subject(subject=physical_sub)
teacher_1.add_subject(subject=world_around_us_sub)
teacher_1.add_subject(subject=nature_and_society_sub)
teacher_1.add_subject(subject=music_sub)
teacher_1.add_subject(subject=art_sub)
school_ck.hire_teacher(teacher=teacher_1)

teacher_2 = Teacher(name="Ivana", surname="Savic", jmbg="1007980735018", date_of_birth="10.7.1980.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="101")
teacher_2.add_subject(subject=math_sub)
teacher_2.add_subject(subject=serbian_sub)
teacher_2.add_subject(subject=english_sub)
teacher_2.add_subject(subject=physical_sub)
teacher_2.add_subject(subject=world_around_us_sub)
teacher_2.add_subject(subject=nature_and_society_sub)
teacher_2.add_subject(subject=music_sub)
teacher_2.add_subject(subject=art_sub)
school_ck.hire_teacher(teacher=teacher_2)

teacher_3 = Teacher(name="Jovan", surname="Ilic", jmbg="0101975730019", date_of_birth="1.1.1975.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="102")
teacher_3.add_subject(subject=math_sub)
teacher_3.add_subject(subject=serbian_sub)
teacher_3.add_subject(subject=english_sub)
teacher_3.add_subject(subject=physical_sub)
teacher_3.add_subject(subject=world_around_us_sub)
teacher_3.add_subject(subject=nature_and_society_sub)
teacher_3.add_subject(subject=music_sub)
teacher_3.add_subject(subject=art_sub)
school_ck.hire_teacher(teacher=teacher_3)

teacher_4 = Teacher(name="Sima", surname="Zivkovic", jmbg="0202975730028", date_of_birth="2.2.1975.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="103")
teacher_4.add_subject(subject=math_sub)
teacher_4.add_subject(subject=serbian_sub)
teacher_4.add_subject(subject=english_sub)
teacher_4.add_subject(subject=physical_sub)
teacher_4.add_subject(subject=world_around_us_sub)
teacher_4.add_subject(subject=nature_and_society_sub)
teacher_4.add_subject(subject=music_sub)
teacher_4.add_subject(subject=art_sub)
school_ss.hire_teacher(teacher=teacher_4)

teacher_5 = Teacher(name="Slavica", surname="Jovic", jmbg="0303976735016", date_of_birth="3.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="104")
teacher_5.add_subject(subject=math_sub)
teacher_5.add_subject(subject=serbian_sub)
teacher_5.add_subject(subject=english_sub)
teacher_5.add_subject(subject=physical_sub)
teacher_5.add_subject(subject=world_around_us_sub)
teacher_5.add_subject(subject=nature_and_society_sub)
teacher_5.add_subject(subject=music_sub)
teacher_5.add_subject(subject=art_sub)
school_ss.hire_teacher(teacher=teacher_5)

teacher_6 = Teacher(name="Milan", surname="Milic", jmbg="0403976730019", date_of_birth="4.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="105")
teacher_6.add_subject(subject=math_sub)
teacher_6.add_subject(subject=serbian_sub)
teacher_6.add_subject(subject=english_sub)
teacher_6.add_subject(subject=physical_sub)
teacher_6.add_subject(subject=world_around_us_sub)
teacher_6.add_subject(subject=nature_and_society_sub)
teacher_6.add_subject(subject=music_sub)
teacher_6.add_subject(subject=art_sub)
school_ss.hire_teacher(teacher=teacher_6)

teacher_7 = Teacher(name="Srdjan", surname="Stosic", jmbg="0503976730013", date_of_birth="5.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="106")
teacher_7.add_subject(subject=math_sub)
school_ck.hire_teacher(teacher=teacher_7)

teacher_8 = Teacher(name="Ana", surname="Pavlovic", jmbg="0603976735001", date_of_birth="6.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="107")
teacher_8.add_subject(subject=math_sub)
school_ss.hire_teacher(teacher=teacher_8)

teacher_9 = Teacher(name="Milena", surname="Dragic", jmbg="0703976735006", date_of_birth="7.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="108")
teacher_9.add_subject(subject=serbian_sub)
school_ck.hire_teacher(teacher=teacher_9)

teacher_10 = Teacher(name="Milica", surname="Mitic", jmbg="0803976735019", date_of_birth="8.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="109")
teacher_10.add_subject(subject=serbian_sub)
school_ss.hire_teacher(teacher=teacher_10)

teacher_11 = Teacher(name="Nikola", surname="Petrovic", jmbg="0903976730011", date_of_birth="9.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="110")
teacher_11.add_subject(subject=english_sub)
school_ck.hire_teacher(teacher=teacher_11)

teacher_12 = Teacher(name="Goran", surname="Nastic", jmbg="1003976730014", date_of_birth="10.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="111")
teacher_12.add_subject(subject=english_sub)
school_ss.hire_teacher(teacher=teacher_12)

teacher_13 = Teacher(name="Zlata", surname="Savic", jmbg="1103976735002", date_of_birth="11.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="112")
teacher_13.add_subject(subject=music_sub)
school_ck.hire_teacher(teacher=teacher_13)

teacher_14 = Teacher(name="Nebojsa", surname="Pavlovic", jmbg="1203976730013", date_of_birth="12.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="113")
teacher_14.add_subject(subject=music_sub)
school_ss.hire_teacher(teacher=teacher_14)

teacher_15 = Teacher(name="Milena", surname="Krstic", jmbg="1303976735001", date_of_birth="13.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="114")
teacher_15.add_subject(subject=art_sub)
school_ck.hire_teacher(teacher=teacher_15)

teacher_16 = Teacher(name="Aca", surname="Petrovic", jmbg="1403976730012", date_of_birth="14.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="115")
teacher_16.add_subject(subject=art_sub)
school_ss.hire_teacher(teacher=teacher_16)

teacher_17 = Teacher(name="Vlada", surname="Stosic", jmbg="1503976730017", date_of_birth="15.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="116")
teacher_17.add_subject(subject=history_sub)
school_ck.hire_teacher(teacher=teacher_17)

teacher_18 = Teacher(name="Tanja", surname="Cvetkovic", jmbg="1603976735005", date_of_birth="16.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="117")
teacher_18.add_subject(subject=history_sub)
school_ss.hire_teacher(teacher=teacher_18)

teacher_19 = Teacher(name="Goran", surname="Lalic", jmbg="1703976730016", date_of_birth="17.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="118")
teacher_19.add_subject(subject=biology_sub)
school_ck.hire_teacher(teacher=teacher_19)

teacher_20 = Teacher(name="Olja", surname="Tosic", jmbg="1803976735004", date_of_birth="18.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="119")
teacher_20.add_subject(subject=biology_sub)
school_ss.hire_teacher(teacher=teacher_20)

teacher_21 = Teacher(name="Ilija", surname="Nikolic", jmbg="1903976730015", date_of_birth="19.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="120")
teacher_21.add_subject(subject=geography_sub)
school_ck.hire_teacher(teacher=teacher_21)

teacher_22 = Teacher(name="Ivana", surname="Ivanovic", jmbg="2003976735001", date_of_birth="20.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="121")
teacher_22.add_subject(subject=geography_sub)
school_ss.hire_teacher(teacher=teacher_22)

teacher_23 = Teacher(name="Andrija", surname="Stojkovic", jmbg="2103976730012", date_of_birth="21.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="122")
teacher_23.add_subject(subject=technology_sub)
school_ck.hire_teacher(teacher=teacher_23)

teacher_24 = Teacher(name="Tamara", surname="Zaric", jmbg="2203976735019", date_of_birth="22.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="123")
teacher_24.add_subject(subject=technology_sub)
school_ss.hire_teacher(teacher=teacher_24)

teacher_25 = Teacher(name="Milutin", surname="Mitic", jmbg="2303976730011", date_of_birth="23.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="124")
teacher_25.add_subject(subject=computer_science_sub)
school_ck.hire_teacher(teacher=teacher_25)

teacher_26 = Teacher(name="Kristina", surname="Savic", jmbg="2403976735018", date_of_birth="24.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="125")
teacher_26.add_subject(subject=computer_science_sub)
school_ss.hire_teacher(teacher=teacher_26)

teacher_27 = Teacher(name="Jovan", surname="Jocic", jmbg="2503976730002", date_of_birth="25.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="126")
teacher_27.add_subject(subject=physics_sub)
school_ck.hire_teacher(teacher=teacher_27)

teacher_28 = Teacher(name="Ivan", surname="Ilic", jmbg="2603976730015", date_of_birth="26.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="127")
teacher_28.add_subject(subject=physics_sub)
school_ss.hire_teacher(teacher=teacher_28)

teacher_29 = Teacher(name="Sara", surname="Saric", jmbg="2703976735003", date_of_birth="27.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="128")
teacher_29.add_subject(subject=chemistry_sub)
school_ck.hire_teacher(teacher=teacher_29)

teacher_30 = Teacher(name="Andjela", surname="Rasic", jmbg="2803976735008", date_of_birth="28.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="129")
teacher_30.add_subject(subject=chemistry_sub)
school_ss.hire_teacher(teacher=teacher_30)

teacher_31 = Teacher(name="Sandra", surname="Dasic", jmbg="2903976735002", date_of_birth="29.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="130")
teacher_31.add_subject(subject=physical_sub)
school_ck.hire_teacher(teacher=teacher_31)

teacher_32 = Teacher(name="Jasmina", surname="Misic", jmbg="3003976735005", date_of_birth="30.3.1976.", country_of_birth="Srbija", city_of_birth="Nis", subjects=[], id="131")
teacher_32.add_subject(subject=physical_sub)
school_ss.hire_teacher(teacher=teacher_32)


student_1 = Student(name="Aleksa", surname="Aleksic", jmbg="0101015730006", date_of_birth="1.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="1", id="1000")
school_ck.add_student_to_school(student=student_1)
first_grade_ck.add_student(student=student_1)
grade_class_1_first_grade_ck.add_student(student=student_1)
student_2 = Student(name="Milan", surname="Milic", jmbg="0201015730019", date_of_birth="2.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="1", id="1001")
school_ck.add_student_to_school(student=student_2)
first_grade_ck.add_student(student=student_2)
grade_class_1_first_grade_ck.add_student(student=student_2)
student_3 = Student(name="Stefan", surname="Stefic", jmbg="0301015730005", date_of_birth="3.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="1", id="1002")
school_ck.add_student_to_school(student=student_3)
first_grade_ck.add_student(student=student_3)
grade_class_1_first_grade_ck.add_student(student=student_3)
student_4 = Student(name="Ana", surname="Anic", jmbg="0401015735001", date_of_birth="4.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="2", id="1003")
school_ck.add_student_to_school(student=student_4)
first_grade_ck.add_student(student=student_4)
grade_class_2_first_grade_ck.add_student(student=student_4)
student_5 = Student(name="Milica", surname="Milic", jmbg="0501015735006", date_of_birth="5.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="2", id="1004")
school_ck.add_student_to_school(student=student_5)
first_grade_ck.add_student(student=student_5)
grade_class_2_first_grade_ck.add_student(student=student_5)
student_6 = Student(name="Joca", surname="Jocic", jmbg="0601015730009", date_of_birth="6.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="2", id="1005")
school_ck.add_student_to_school(student=student_6)
first_grade_ck.add_student(student=student_6)
grade_class_2_first_grade_ck.add_student(student=student_6)

student_7 = Student(name="Milja", surname="Mikic", jmbg="0701015735005", date_of_birth="7.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="1", id="1006")
school_ss.add_student_to_school(student=student_7)
first_grade_ss.add_student(student=student_7)
grade_class_1_first_grade_ss.add_student(student=student_7)
student_8 = Student(name="Janko", surname="Jankic", jmbg="0801015730008", date_of_birth="8.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="1", id="1007")
school_ss.add_student_to_school(student=student_8)
first_grade_ss.add_student(student=student_8)
grade_class_1_first_grade_ss.add_student(student=student_8)
student_9 = Student(name="Zdravko", surname="Zdravkic", jmbg="0901015730002", date_of_birth="9.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="1", id="1008")
school_ss.add_student_to_school(student=student_9)
first_grade_ss.add_student(student=student_9)
grade_class_1_first_grade_ss.add_student(student=student_9)
student_10 = Student(name="Sara", surname="Saric", jmbg="1001015735007", date_of_birth="10.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="2", id="1009")
school_ss.add_student_to_school(student=student_10)
first_grade_ss.add_student(student=student_10)
grade_class_2_first_grade_ss.add_student(student=student_10)
student_11 = Student(name="Milica", surname="Tasic", jmbg="1101015735001", date_of_birth="11.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="2", id="1010")
school_ss.add_student_to_school(student=student_11)
first_grade_ss.add_student(student=student_11)
grade_class_2_first_grade_ss.add_student(student=student_11)
student_12 = Student(name="Maja", surname="Jocic", jmbg="1201015735006", date_of_birth="12.1.2015.", country_of_birth="Srbija", city_of_birth="Nis", grade="I", grade_class="2", id="1011")
school_ss.add_student_to_school(student=student_12)
first_grade_ss.add_student(student=student_12)
grade_class_2_first_grade_ss.add_student(student=student_12)

student_13 = Student(name="Sava", surname="Ciric", jmbg="0101014730002", date_of_birth="1.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="1", id="1012")
school_ck.add_student_to_school(student=student_13)
second_grade_ck.add_student(student=student_13)
grade_class_1_second_grade_ck.add_student(student=student_13)
student_14 = Student(name="Mateja", surname="Pesic", jmbg="0201014730007", date_of_birth="2.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="1", id="1013")
school_ck.add_student_to_school(student=student_14)
second_grade_ck.add_student(student=student_14)
grade_class_1_second_grade_ck.add_student(student=student_14)
student_15 = Student(name="Goran", surname="Brkic", jmbg="0301014730001", date_of_birth="3.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="1", id="1014")
school_ck.add_student_to_school(student=student_15)
second_grade_ck.add_student(student=student_15)
grade_class_1_second_grade_ck.add_student(student=student_15)
student_16 = Student(name="Milan", surname="Pesic", jmbg="0401014730006", date_of_birth="4.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="2", id="1015")
school_ck.add_student_to_school(student=student_16)
second_grade_ck.add_student(student=student_16)
grade_class_2_second_grade_ck.add_student(student=student_16)
student_17 = Student(name="Maja", surname="Manic", jmbg="0501014735002", date_of_birth="5.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="2", id="1016")
school_ck.add_student_to_school(student=student_17)
second_grade_ck.add_student(student=student_17)
grade_class_2_second_grade_ck.add_student(student=student_17)
student_18 = Student(name="Mila", surname="Milic", jmbg="0601014735007", date_of_birth="6.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="2", id="1017")
school_ck.add_student_to_school(student=student_18)
second_grade_ck.add_student(student=student_18)
grade_class_2_second_grade_ck.add_student(student=student_18)
student_19 = Student(name="Simona", surname="Jelic", jmbg="0701014735001", date_of_birth="7.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="1", id="1018")
school_ss.add_student_to_school(student=student_19)
second_grade_ss.add_student(student=student_19)

grade_class_1_second_grade_ss.add_student(student=student_19)
student_20 = Student(name="Andjela", surname="Igic", jmbg="0801014735006", date_of_birth="8.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="1", id="1019")
school_ss.add_student_to_school(student=student_20)
second_grade_ss.add_student(student=student_20)
grade_class_1_second_grade_ss.add_student(student=student_20)
student_21 = Student(name="Sandra", surname="Nikolic", jmbg="0901014735019", date_of_birth="9.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="1", id="1020")
school_ss.add_student_to_school(student=student_21)
second_grade_ss.add_student(student=student_21)
grade_class_1_second_grade_ss.add_student(student=student_21)
student_22 = Student(name="Aca", surname="Petrovic", jmbg="1001014730001", date_of_birth="10.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="2", id="1021")
school_ss.add_student_to_school(student=student_22)
second_grade_ss.add_student(student=student_22)
grade_class_2_second_grade_ss.add_student(student=student_22)
student_23 = Student(name="Andrija", surname="Igic", jmbg="1101014730006", date_of_birth="11.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="2", id="1022")
school_ss.add_student_to_school(student=student_23)
second_grade_ss.add_student(student=student_23)
grade_class_2_second_grade_ss.add_student(student=student_23)
student_24 = Student(name="Vuk", surname="Vukic", jmbg="1201014730019", date_of_birth="12.1.2014.", country_of_birth="Srbija", city_of_birth="Nis", grade="II", grade_class="2", id="1023")
school_ss.add_student_to_school(student=student_24)
second_grade_ss.add_student(student=student_24)
grade_class_2_second_grade_ss.add_student(student=student_24)

student_25 = Student(name="Eva", surname="Jelic", jmbg="0101013735019", date_of_birth="1.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="1", id="1024")
school_ck.add_student_to_school(student=student_25)
third_grade_ck.add_student(student=student_25)
grade_class_1_third_grade_ck.add_student(student=student_25)
student_26 = Student(name="Lana", surname="Stosic", jmbg="0201013735005", date_of_birth="2.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="1", id="1025")
school_ck.add_student_to_school(student=student_26)
third_grade_ck.add_student(student=student_26)
grade_class_1_third_grade_ck.add_student(student=student_26)
student_27 = Student(name="Olja", surname="Cvetkovic", jmbg="0301013735018", date_of_birth="3.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="1", id="1026")
school_ck.add_student_to_school(student=student_27)
third_grade_ck.add_student(student=student_27)
grade_class_1_third_grade_ck.add_student(student=student_27)
student_28 = Student(name="Tina", surname="Pesic", jmbg="0401013735004", date_of_birth="4.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="2", id="1027")
school_ck.add_student_to_school(student=student_28)
third_grade_ck.add_student(student=student_28)
grade_class_2_third_grade_ck.add_student(student=student_28)
student_29 = Student(name="Ilija", surname="Igic", jmbg="0501013730007", date_of_birth="5.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="2", id="1028")
school_ck.add_student_to_school(student=student_29)
third_grade_ck.add_student(student=student_29)
grade_class_2_third_grade_ck.add_student(student=student_29)
student_30 = Student(name="Nikola", surname="Stojic", jmbg="0601013730001", date_of_birth="6.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="2", id="1029")
school_ck.add_student_to_school(student=student_30)
third_grade_ck.add_student(student=student_30)
grade_class_2_third_grade_ck.add_student(student=student_30)

student_31 = Student(name="Zika", surname="Zikic", jmbg="0701013730006", date_of_birth="7.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="1", id="1030")
school_ss.add_student_to_school(student=student_31)
third_grade_ss.add_student(student=student_31)
grade_class_1_third_grade_ss.add_student(student=student_31)
student_32 = Student(name="Pera", surname="Peric", jmbg="0801013730017", date_of_birth="8.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="1", id="1031")
school_ss.add_student_to_school(student=student_32)
third_grade_ss.add_student(student=student_32)
grade_class_1_third_grade_ss.add_student(student=student_32)
student_33 = Student(name="Mita", surname="Mitic", jmbg="0901013730005", date_of_birth="9.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="1", id="1032")
school_ss.add_student_to_school(student=student_33)
third_grade_ss.add_student(student=student_33)
grade_class_1_third_grade_ss.add_student(student=student_33)
student_34 = Student(name="Mina", surname="Savic", jmbg="1001013735018", date_of_birth="10.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="2", id="1033")
school_ss.add_student_to_school(student=student_34)
third_grade_ss.add_student(student=student_34)
grade_class_2_third_grade_ss.add_student(student=student_34)
student_35 = Student(name="Kristina", surname="Babic", jmbg="1101013735004", date_of_birth="11.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="2", id="1034")
school_ss.add_student_to_school(student=student_35)
third_grade_ss.add_student(student=student_35)
grade_class_2_third_grade_ss.add_student(student=student_35)
student_36 = Student(name="Marija", surname="Vukic", jmbg="1201013735009", date_of_birth="12.1.2013.", country_of_birth="Srbija", city_of_birth="Nis", grade="III", grade_class="2", id="1035")
school_ss.add_student_to_school(student=student_36)
third_grade_ss.add_student(student=student_36)
grade_class_2_third_grade_ss.add_student(student=student_36)

student_37 = Student(name="Pavle", surname="Bakic", jmbg="0101012730005", date_of_birth="1.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="1", id="1036")
school_ck.add_student_to_school(student=student_37)
fourth_grade_ck.add_student(student=student_37)
grade_class_1_fourth_grade_ck.add_student(student=student_37)
student_38 = Student(name="Mijat", surname="Krkic", jmbg="0201012730018", date_of_birth="2.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="1", id="1037")
school_ck.add_student_to_school(student=student_38)
fourth_grade_ck.add_student(student=student_38)
grade_class_1_fourth_grade_ck.add_student(student=student_38)
student_39 = Student(name="Sofija", surname="Lalic", jmbg="0301012735006", date_of_birth="3.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="1", id="1038")
school_ck.add_student_to_school(student=student_39)
fourth_grade_ck.add_student(student=student_39)
grade_class_1_fourth_grade_ck.add_student(student=student_39)
student_40 = Student(name="Lola", surname="Kocic", jmbg="0401012735019", date_of_birth="4.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="2", id="1039")
school_ck.add_student_to_school(student=student_40)
fourth_grade_ck.add_student(student=student_40)
grade_class_2_fourth_grade_ck.add_student(student=student_40)
student_41 = Student(name="Kaja", surname="Miletic", jmbg="0501012735005", date_of_birth="5.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="2", id="1040")
school_ck.add_student_to_school(student=student_41)
fourth_grade_ck.add_student(student=student_41)
grade_class_2_fourth_grade_ck.add_student(student=student_41)
student_42 = Student(name="Milica", surname="Milenkovic", jmbg="0601012735018", date_of_birth="6.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="2", id="1041")
school_ck.add_student_to_school(student=student_42)
fourth_grade_ck.add_student(student=student_42)
grade_class_2_fourth_grade_ck.add_student(student=student_42)

student_43 = Student(name="Vasa", surname="Tomic", jmbg="0701012730002", date_of_birth="7.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="1", id="1042")
school_ss.add_student_to_school(student=student_43)
fourth_grade_ss.add_student(student=student_43)
grade_class_1_fourth_grade_ss.add_student(student=student_43)
student_44 = Student(name="Mitar", surname="Mitic", jmbg="0801012730007", date_of_birth="8.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="1", id="1043")
school_ss.add_student_to_school(student=student_44)
fourth_grade_ss.add_student(student=student_44)
grade_class_1_fourth_grade_ss.add_student(student=student_44)
student_45 = Student(name="Vlada", surname="Stosic", jmbg="0901012730001", date_of_birth="9.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="1", id="1044")
school_ss.add_student_to_school(student=student_45)
fourth_grade_ss.add_student(student=student_45)
grade_class_1_fourth_grade_ss.add_student(student=student_45)
student_46 = Student(name="Visnja", surname="Simic", jmbg="1001012735006", date_of_birth="10.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="2", id="1045")
school_ss.add_student_to_school(student=student_46)
fourth_grade_ss.add_student(student=student_46)
grade_class_2_fourth_grade_ss.add_student(student=student_46)
student_47 = Student(name="Kala", surname="Kocic", jmbg="1101012735019", date_of_birth="11.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="2", id="1046")
school_ss.add_student_to_school(student=student_47)
fourth_grade_ss.add_student(student=student_47)
grade_class_2_fourth_grade_ss.add_student(student=student_47)
student_48 = Student(name="Sava", surname="Tadic", jmbg="1201012730003", date_of_birth="12.1.2012.", country_of_birth="Srbija", city_of_birth="Nis", grade="IV", grade_class="2", id="1047")
school_ss.add_student_to_school(student=student_48)
fourth_grade_ss.add_student(student=student_48)
grade_class_2_fourth_grade_ss.add_student(student=student_48)

student_49 = Student(name="Sasa", surname="Popic", jmbg="0101011730001", date_of_birth="1.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="1", id="1048")
school_ck.add_student_to_school(student=student_49)
fifth_grade_ck.add_student(student=student_49)
grade_class_1_fifth_grade_ck.add_student(student=student_49)
student_50 = Student(name="Lela", surname="Lelic", jmbg="0201011735008", date_of_birth="2.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="1", id="1049")
school_ck.add_student_to_school(student=student_50)
fifth_grade_ck.add_student(student=student_50)
grade_class_1_fifth_grade_ck.add_student(student=student_50)
student_51 = Student(name="Vlada", surname="Makic", jmbg="0301011730019", date_of_birth="3.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="1", id="1050")
school_ck.add_student_to_school(student=student_51)
fifth_grade_ck.add_student(student=student_51)
grade_class_1_fifth_grade_ck.add_student(student=student_51)
student_52 = Student(name="Sara", surname="Simic", jmbg="0401011735007", date_of_birth="4.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="2", id="1051")
school_ck.add_student_to_school(student=student_52)
fifth_grade_ck.add_student(student=student_52)
grade_class_2_fifth_grade_ck.add_student(student=student_52)
student_53 = Student(name="Vesko", surname="Smiljic", jmbg="0501011730018", date_of_birth="5.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="2", id="1052")
school_ck.add_student_to_school(student=student_53)
fifth_grade_ck.add_student(student=student_53)
grade_class_2_fifth_grade_ck.add_student(student=student_53)
student_54 = Student(name="Sava", surname="Hodzic", jmbg="0601011730004", date_of_birth="6.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="2", id="1053")
school_ck.add_student_to_school(student=student_54)
fifth_grade_ck.add_student(student=student_54)
grade_class_2_fifth_grade_ck.add_student(student=student_54)

student_55 = Student(name="Sveta", surname="Nastic", jmbg="0701011730009", date_of_birth="7.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="1", id="1054")
school_ss.add_student_to_school(student=student_55)
fifth_grade_ss.add_student(student=student_55)
grade_class_1_fifth_grade_ss.add_student(student=student_55)
student_56 = Student(name="Srna", surname="Dasic", jmbg="0801011735005", date_of_birth="8.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="1", id="1055")
school_ss.add_student_to_school(student=student_56)
fifth_grade_ss.add_student(student=student_56)
grade_class_1_fifth_grade_ss.add_student(student=student_56)
student_57 = Student(name="Dasa", surname="Stosic", jmbg="0901011735018", date_of_birth="9.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="1", id="1056")
school_ss.add_student_to_school(student=student_57)
fifth_grade_ss.add_student(student=student_57)
grade_class_1_fifth_grade_ss.add_student(student=student_57)
student_58 = Student(name="Ema", surname="Obilic", jmbg="1001011735002", date_of_birth="10.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="2", id="1057")
school_ss.add_student_to_school(student=student_58)
fifth_grade_ss.add_student(student=student_58)
grade_class_2_fifth_grade_ss.add_student(student=student_58)
student_59 = Student(name="Rastko", surname="Cetic", jmbg="1101011730005", date_of_birth="11.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="2", id="1058")
school_ss.add_student_to_school(student=student_59)
fifth_grade_ss.add_student(student=student_59)
grade_class_2_fifth_grade_ss.add_student(student=student_59)
student_60 = Student(name="Jova", surname="Tadic", jmbg="1201011730018", date_of_birth="12.1.2011.", country_of_birth="Srbija", city_of_birth="Nis", grade="V", grade_class="2", id="1059")
school_ss.add_student_to_school(student=student_60)
fifth_grade_ss.add_student(student=student_60)
grade_class_2_fifth_grade_ss.add_student(student=student_60)

student_61 = Student(name="Maja", surname="Nastic", jmbg="0101010735018", date_of_birth="1.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="1", id="1060")
school_ck.add_student_to_school(student=student_61)
sixth_grade_ck.add_student(student=student_61)
grade_class_1_sixth_grade_ck.add_student(student=student_61)
student_62 = Student(name="Lana", surname="Lanic", jmbg="0201010735004", date_of_birth="2.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="1", id="1061")
school_ck.add_student_to_school(student=student_62)
sixth_grade_ck.add_student(student=student_62)
grade_class_1_sixth_grade_ck.add_student(student=student_62)
student_63 = Student(name="Sima", surname="Simic", jmbg="0301010730007", date_of_birth="3.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="1", id="1062")
school_ck.add_student_to_school(student=student_63)
sixth_grade_ck.add_student(student=student_63)
grade_class_1_sixth_grade_ck.add_student(student=student_63)
student_64 = Student(name="Marko", surname="Markovic", jmbg="0401010730001", date_of_birth="4.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="2", id="1063")
school_ck.add_student_to_school(student=student_64)
sixth_grade_ck.add_student(student=student_64)
grade_class_2_sixth_grade_ck.add_student(student=student_64)
student_65 = Student(name="Jovana", surname="Jovanovic", jmbg="0501010735008", date_of_birth="5.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="2", id="1064")
school_ck.add_student_to_school(student=student_65)
sixth_grade_ck.add_student(student=student_65)
grade_class_2_sixth_grade_ck.add_student(student=student_65)
student_66 = Student(name="Jovan", surname="Jovanovic", jmbg="0601010730019", date_of_birth="6.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="2", id="1065")
school_ck.add_student_to_school(student=student_66)
sixth_grade_ck.add_student(student=student_66)
grade_class_2_sixth_grade_ck.add_student(student=student_66)

student_67 = Student(name="Lara", surname="Laric", jmbg="0701010735007", date_of_birth="7.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="1", id="1066")
school_ss.add_student_to_school(student=student_67)
sixth_grade_ss.add_student(student=student_67)
grade_class_1_sixth_grade_ss.add_student(student=student_67)
student_68 = Student(name="Cveta", surname="Cvetic", jmbg="0801010735001", date_of_birth="8.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="1", id="1067")
school_ss.add_student_to_school(student=student_68)
sixth_grade_ss.add_student(student=student_68)
grade_class_1_sixth_grade_ss.add_student(student=student_68)
student_69 = Student(name="Srdjan", surname="Stosic", jmbg="0901010730004", date_of_birth="9.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="1", id="1068")
school_ss.add_student_to_school(student=student_69)
sixth_grade_ss.add_student(student=student_69)
grade_class_1_sixth_grade_ss.add_student(student=student_69)
student_70 = Student(name="Jakov", surname="Ilic", jmbg="1001010730007", date_of_birth="10.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="2", id="1069")
school_ss.add_student_to_school(student=student_70)
sixth_grade_ss.add_student(student=student_70)
grade_class_2_sixth_grade_ss.add_student(student=student_70)
student_71 = Student(name="Ognjen", surname="Matic", jmbg="1101010730001", date_of_birth="11.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="2", id="1070")
school_ss.add_student_to_school(student=student_71)
sixth_grade_ss.add_student(student=student_71)
grade_class_2_sixth_grade_ss.add_student(student=student_71)
student_72 = Student(name="Filip", surname="Tadic", jmbg="1201010730006", date_of_birth="12.1.2010.", country_of_birth="Srbija", city_of_birth="Nis", grade="VI", grade_class="2", id="1071")
school_ss.add_student_to_school(student=student_72)
sixth_grade_ss.add_student(student=student_72)
grade_class_2_sixth_grade_ss.add_student(student=student_72)

student_73 = Student(name="Mila", surname="Laric", jmbg="0101009735004", date_of_birth="1.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="1", id="1072")
school_ck.add_student_to_school(student=student_73)
seventh_grade_ck.add_student(student=student_73)
grade_class_1_seventh_grade_ck.add_student(student=student_73)
student_74 = Student(name="Stefan", surname="Cvetic", jmbg="0201009730007", date_of_birth="2.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="1", id="1073")
school_ck.add_student_to_school(student=student_74)
seventh_grade_ck.add_student(student=student_74)
grade_class_1_seventh_grade_ck.add_student(student=student_74)
student_75 = Student(name="Jovan", surname="Stosic", jmbg="0301009730001", date_of_birth="3.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="1", id="1074")
school_ck.add_student_to_school(student=student_75)
seventh_grade_ck.add_student(student=student_75)
grade_class_1_seventh_grade_ck.add_student(student=student_75)
student_76 = Student(name="Lana", surname="Ilic", jmbg="0401009735008", date_of_birth="4.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="2", id="1075")
school_ck.add_student_to_school(student=student_76)
seventh_grade_ck.add_student(student=student_76)
grade_class_2_seventh_grade_ck.add_student(student=student_76)
student_77 = Student(name="Milica", surname="Matic", jmbg="0501009735002", date_of_birth="5.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="2", id="1076")
school_ck.add_student_to_school(student=student_77)
seventh_grade_ck.add_student(student=student_77)
grade_class_2_seventh_grade_ck.add_student(student=student_77)
student_78 = Student(name="Kristina", surname="Tadic", jmbg="0601009735007", date_of_birth="6.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="2", id="1077")
school_ck.add_student_to_school(student=student_78)
seventh_grade_ck.add_student(student=student_78)
grade_class_2_seventh_grade_ck.add_student(student=student_78)


student_79 = Student(name="Katarina", surname="Laric", jmbg="0701009735001", date_of_birth="7.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="1", id="1078")
school_ss.add_student_to_school(student=student_79)
seventh_grade_ss.add_student(student=student_79)
grade_class_1_seventh_grade_ss.add_student(student=student_79)
student_80 = Student(name="Pera", surname="Cvetic", jmbg="0801009730004", date_of_birth="8.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="1", id="1079")
school_ss.add_student_to_school(student=student_80)
seventh_grade_ss.add_student(student=student_80)
grade_class_1_seventh_grade_ss.add_student(student=student_80)
student_81 = Student(name="Zika", surname="Stosic", jmbg="0901009730009", date_of_birth="9.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="1", id="1080")
school_ss.add_student_to_school(student=student_81)
seventh_grade_ss.add_student(student=student_81)
grade_class_1_seventh_grade_ss.add_student(student=student_81)
student_82 = Student(name="Laza", surname="Ilic", jmbg="1001009730001", date_of_birth="10.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="2", id="1081")
school_ss.add_student_to_school(student=student_82)
seventh_grade_ss.add_student(student=student_82)
grade_class_2_seventh_grade_ss.add_student(student=student_82)
student_83 = Student(name="Mika", surname="Matic", jmbg="1101009730006", date_of_birth="11.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="2", id="1082")
school_ss.add_student_to_school(student=student_83)
seventh_grade_ss.add_student(student=student_83)
grade_class_2_seventh_grade_ss.add_student(student=student_83)
student_84 = Student(name="Toma", surname="Tadic", jmbg="1201009730019", date_of_birth="12.1.2009.", country_of_birth="Srbija", city_of_birth="Nis", grade="VII", grade_class="2", id="1083")
school_ss.add_student_to_school(student=student_84)
seventh_grade_ss.add_student(student=student_84)
grade_class_2_seventh_grade_ss.add_student(student=student_84)

student_85 = Student(name="Mila", surname="Laric", jmbg="0101008735019", date_of_birth="1.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="1", id="1084")
school_ck.add_student_to_school(student=student_85)
eight_grade_ck.add_student(student=student_85)
grade_class_1_eight_grade_ck.add_student(student=student_85)
student_86 = Student(name="Neda", surname="Cvetic", jmbg="0201008735005", date_of_birth="2.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="1", id="1085")
school_ck.add_student_to_school(student=student_86)
eight_grade_ck.add_student(student=student_86)
grade_class_1_eight_grade_ck.add_student(student=student_86)
student_87 = Student(name="Voja", surname="Stosic", jmbg="0301008730008", date_of_birth="3.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="1", id="1086")
school_ck.add_student_to_school(student=student_87)
eight_grade_ck.add_student(student=student_87)
grade_class_1_eight_grade_ck.add_student(student=student_87)
student_88 = Student(name="Danica", surname="Ilic", jmbg="0401008735004", date_of_birth="4.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="2", id="1087")
school_ck.add_student_to_school(student=student_88)
eight_grade_ck.add_student(student=student_88)
grade_class_2_eight_grade_ck.add_student(student=student_88)
student_89 = Student(name="Milena", surname="Matic", jmbg="0501008735009", date_of_birth="5.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="2", id="1088")
school_ck.add_student_to_school(student=student_89)
eight_grade_ck.add_student(student=student_89)
grade_class_2_eight_grade_ck.add_student(student=student_89)
student_90 = Student(name="Filip", surname="Simic", jmbg="0601008730001", date_of_birth="6.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="2", id="1089")
school_ck.add_student_to_school(student=student_90)
eight_grade_ck.add_student(student=student_90)
grade_class_2_eight_grade_ck.add_student(student=student_90)

student_91 = Student(name="Dana", surname="Laric", jmbg="0701008735008", date_of_birth="7.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="1", id="1090")
school_ss.add_student_to_school(student=student_91)
eight_grade_ss.add_student(student=student_91)
grade_class_1_eight_grade_ss.add_student(student=student_91)
student_92 = Student(name="Veljko", surname="Cvetic", jmbg="0801008730019", date_of_birth="8.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="1", id="1091")
school_ss.add_student_to_school(student=student_92)
eight_grade_ss.add_student(student=student_92)
grade_class_1_eight_grade_ss.add_student(student=student_92)
student_93 = Student(name="Dusan", surname="Stosic", jmbg="0901008730005", date_of_birth="9.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="1", id="1092")
school_ss.add_student_to_school(student=student_93)
eight_grade_ss.add_student(student=student_93)
grade_class_1_eight_grade_ss.add_student(student=student_93)
student_94 = Student(name="Milan", surname="Ilic", jmbg="1001008730008", date_of_birth="10.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="2", id="1093")
school_ss.add_student_to_school(student=student_94)
eight_grade_ss.add_student(student=student_94)
grade_class_2_eight_grade_ss.add_student(student=student_94)
student_95 = Student(name="Nemanja", surname="Matic", jmbg="1101008730002", date_of_birth="11.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="2", id="1094")
school_ss.add_student_to_school(student=student_95)
eight_grade_ss.add_student(student=student_95)
grade_class_2_eight_grade_ss.add_student(student=student_95)
student_96 = Student(name="Uros", surname="Tadic", jmbg="1201008730007", date_of_birth="12.1.2008.", country_of_birth="Srbija", city_of_birth="Nis", grade="VIII", grade_class="2", id="1095")
school_ss.add_student_to_school(student=student_96)
eight_grade_ss.add_student(student=student_96)
grade_class_2_eight_grade_ss.add_student(student=student_96)

first_grade_ck.assign_subjects_to_students()
first_grade_ss.assign_subjects_to_students()
second_grade_ck.assign_subjects_to_students()
second_grade_ss.assign_subjects_to_students()
third_grade_ck.assign_subjects_to_students()
third_grade_ss.assign_subjects_to_students()
fourth_grade_ck.assign_subjects_to_students()
fourth_grade_ss.assign_subjects_to_students()
fifth_grade_ck.assign_subjects_to_students()
fifth_grade_ss.assign_subjects_to_students()
sixth_grade_ck.assign_subjects_to_students()
sixth_grade_ss.assign_subjects_to_students()
seventh_grade_ck.assign_subjects_to_students()
seventh_grade_ss.assign_subjects_to_students()
eight_grade_ck.assign_subjects_to_students()
eight_grade_ss.assign_subjects_to_students()


school_ck.add_grade(grade=first_grade_ck)
school_ck.add_grade(grade=second_grade_ck)
school_ck.add_grade(grade=third_grade_ck)
school_ck.add_grade(grade=fourth_grade_ck)
school_ck.add_grade(grade=fifth_grade_ck)
school_ck.add_grade(grade=sixth_grade_ck)
school_ck.add_grade(grade=seventh_grade_ck)
school_ck.add_grade(grade=eight_grade_ck)
school_ss.add_grade(grade=first_grade_ss)
school_ss.add_grade(grade=second_grade_ss)
school_ss.add_grade(grade=third_grade_ss)
school_ss.add_grade(grade=fourth_grade_ss)
school_ss.add_grade(grade=fifth_grade_ss)
school_ss.add_grade(grade=sixth_grade_ss)
school_ss.add_grade(grade=seventh_grade_ss)
school_ss.add_grade(grade=eight_grade_ss)

school_ck.assign_grade_class_elders()
school_ss.assign_grade_class_elders()

schools = [school_ck, school_ss]
schools_ids = [school_ck.get_school_id(), school_ss.get_school_id()]

grades_for_school_ck = [first_grade_ck, second_grade_ck, third_grade_ck, fourth_grade_ck, fifth_grade_ck, sixth_grade_ck, seventh_grade_ck, eight_grade_ck]
grades_for_school_ss = [first_grade_ss, second_grade_ss, third_grade_ss, fourth_grade_ss, fifth_grade_ss, sixth_grade_ss, seventh_grade_ss, eight_grade_ss]
grade_names = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII"]

elementary_grade_subjects = [math_sub, serbian_sub, english_sub, world_around_us_sub, nature_and_society_sub, art_sub, music_sub, physical_sub]
higher_grade_subjects = [math_sub, serbian_sub, english_sub, art_sub, music_sub, physical_sub, history_sub, geography_sub, biology_sub, physics_sub, chemistry_sub, technology_sub, computer_science_sub]
elementary_grade_subjects_names = [math_sub.name, serbian_sub.name, english_sub.name, world_around_us_sub.name, nature_and_society_sub.name, art_sub.name, music_sub.name, physical_sub.name]
higher_grade_subjects_names = [math_sub.name, serbian_sub.name, english_sub.name, art_sub.name, music_sub.name, physical_sub.name, history_sub.name, geography_sub.name, biology_sub.name, physics_sub.name, chemistry_sub.name, technology_sub.name, computer_science_sub.name]

